# -*- coding: utf-8 -*-
"""app1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZETfL8O8I2wKP6VIFWkaFrecOINoIOj
"""

pip install plotly

!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

!pip install streamlit

# IMPORT LIBRARIES
import pandas as pd
import plotly.express as px
import streamlit as st

# KONFIGURASI DASHBOARD
st.set_page_config(
    page_title="Video Game Sales Dashboard",
    page_icon=":video_game:",
    layout="wide"
)

# TEMA WARNA DASBOR
st.markdown(
    """
    <style>
    .stApp {
        background-color: #F5F5F5;
    }
    .stButton>button {
        background-color: #0083B8;
        color: white;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
    }
    .stButton>button:hover {
        background-color: #005f8c;
        color: white;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# IMPORT DATASET
df = pd.read_csv("vgsales.csv")
df = df.dropna(subset=["Year", "Publisher", "Genre", "Platform", "Global_Sales"])
df["Year"] = df["Year"].astype(int)

# HEADER
st.title(":video_game: Video Game Sales Dashboard")
klik = st.button("Click Here for Credit")
if klik:
    st.write("Created by redya08")
    st.write("Data Source: vgsales.csv")
st.markdown("##")

# SIDEBAR FILTER
st.sidebar.header("Filter data:")
platform_sb = st.sidebar.multiselect(
    "Pilih Platform:",
    options=df["Platform"].unique(),
    default=df["Platform"].unique()
)

genre_sb = st.sidebar.multiselect(
    "Pilih Genre:",
    options=df["Genre"].unique(),
    default=df["Genre"].unique()
)

year_sb = st.sidebar.multiselect(
    "Pilih Tahun Rilis:",
    options=sorted(df["Year"].unique()),
    default=sorted(df["Year"].unique())
)

# FILTERING DATA
filtered_df = df[
    (df["Platform"].isin(platform_sb)) &
    (df["Genre"].isin(genre_sb)) &
    (df["Year"].isin(year_sb))
]

# KPI
total_game = filtered_df.shape[0]
avg_sales = round(filtered_df["Global_Sales"].mean(), 2)
top_genre = filtered_df["Genre"].value_counts().idxmax()

left, middle, right = st.columns(3)
with left:
    st.subheader("Total Game")
    st.subheader(f"{total_game:,}")
with middle:
    st.subheader("Rata-rata Penjualan Global")
    st.subheader(f"{avg_sales} juta unit")
with right:
    st.subheader("Genre Terpopuler")
    st.subheader(top_genre)

st.markdown("---")

# DATA TABEL
st.dataframe(filtered_df)

# BAR CHART: Penjualan per Genre
sales_per_genre = filtered_df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).reset_index()
fig_genre = px.bar(
    sales_per_genre,
    x="Genre",
    y="Global_Sales",
    title="<b>Penjualan Global per Genre</b>",
    color_discrete_sequence=["#0083B8"],
    template="plotly_white"
)
st.plotly_chart(fig_genre, use_container_width=True)

# LINE CHART: Penjualan per Tahun
sales_per_year = filtered_df.groupby("Year")["Global_Sales"].sum().reset_index()
fig_year = px.line(
    sales_per_year,
    x="Year",
    y="Global_Sales",
    title="<b>Tren Penjualan Global per Tahun</b>",
    markers=True,
    template="plotly_white"
)
st.plotly_chart(fig_year, use_container_width=True)

# PIE CHART: 10 Publisher Teratas
top_publishers = filtered_df["Publisher"].value_counts().head(10).reset_index()
top_publishers.columns = ["Publisher", "Jumlah Game"]
fig_pub = px.pie(
    top_publishers,
    names="Publisher",
    values="Jumlah Game",
    title="<b>10 Publisher dengan Jumlah Game Terbanyak</b>"
)
st.plotly_chart(fig_pub, use_container_width=True)

from google.colab import files
files.download("app1.py")